INSERT INTO "APP"."MODULE"("OID","MODULEID","MODULENAME") VALUES (1, 'sv1', 'AddressBook');
INSERT INTO "APP"."MODULE"("OID","MODULEID","MODULENAME") VALUES (2, 'area5', 'ManageAreas');
INSERT INTO "APP"."MODULE"("OID","MODULEID","MODULENAME") VALUES (3, 'miu3', 'Employee details');


INSERT INTO "APP"."GROUP"("OID","GROUPNAME","MODULE_OID") VALUES (1, 'Administrator', 1);
INSERT INTO "APP"."GROUP"("OID","GROUPNAME","MODULE_OID") VALUES (2, 'Employee', 1);


INSERT INTO "APP"."GROUP_MODULE"("GROUP_OID","MODULE_OID") VALUES (1, 2);
INSERT INTO "APP"."GROUP_MODULE"("GROUP_OID","MODULE_OID") VALUES (1, 3);

INSERT INTO "APP"."ROLE"("OID","NAME") VALUES (1, 'Administrator');
INSERT INTO "APP"."ROLE"("OID","NAME") VALUES (2, 'Employee');


INSERT INTO "APP"."USER"("OID", "USERNAME","PASSWORD","EMAIL","GROUP_OID") VALUES (1, 'John Doe', 'password', 'john.doe@dell.com', 1);
INSERT INTO "APP"."USER"("OID", "USERNAME","PASSWORD","EMAIL","GROUP_OID") VALUES (2, 'Ronald Still', 'password', 'rstill12@lucatel.com', 2);
INSERT INTO "APP"."USER"("OID", "USERNAME","PASSWORD","EMAIL","GROUP_OID") VALUES (3, 'Scott Tiger', 'password', 'tiger@imtec.com', 2);
INSERT INTO "APP"."USER"("OID", "USERNAME","PASSWORD","EMAIL","GROUP_OID") VALUES (4, 'Ray Herbert', 'password', 'herbert@vesuvio.com', 1);
INSERT INTO "APP"."USER"("OID", "USERNAME","PASSWORD","EMAIL","GROUP_OID") VALUES (5, 'Douglas Martin', 'password', 'dmarting@intel.com', 2);
INSERT INTO "APP"."USER"("OID", "USERNAME","PASSWORD","EMAIL","GROUP_OID") VALUES (6, 'Adam Hendricks', 'password', 'ahendricks@intel.com', 2);
INSERT INTO "APP"."USER"("OID", "USERNAME","PASSWORD","EMAIL","GROUP_OID") VALUES (7, 'Mark Walsh', 'password', 'mealsh@tonins.com', 2);
INSERT INTO "APP"."USER"("OID", "USERNAME","PASSWORD","EMAIL","GROUP_OID") VALUES (8, 'James Ning', 'password', 'jning@catuc.com', 2);


INSERT INTO "APP"."EMPLOYEE"("USER_OID", "FIRST_NAME","PHONE","GENDER","LOCATION","BIRTHDATE","IM_USERNAME","PIC","ENTRYDATE","LAST_NAME","ORGANIZATION_UNIT_OID","ROLE_OID") VALUES (1, 'John', '5143514312', 'M', 'NY', '1989-03-08', 'jdoe', 'upload/profile_big.jpg', '2012-10-16', 'Doe', NULL, 1);
INSERT INTO "APP"."EMPLOYEE"("USER_OID", "FIRST_NAME","PHONE","GENDER","LOCATION","BIRTHDATE","IM_USERNAME","PIC","ENTRYDATE","LAST_NAME","ORGANIZATION_UNIT_OID","ROLE_OID") VALUES (2, 'Ronald', '465131518', 'M', 'MA', '1964-12-09', 'rstill', 'upload/profile_big.jpg', '2012-10-16', 'Stil', NULL, 2);
INSERT INTO "APP"."EMPLOYEE"("USER_OID", "FIRST_NAME","PHONE","GENDER","LOCATION","BIRTHDATE","IM_USERNAME","PIC","ENTRYDATE","LAST_NAME","ORGANIZATION_UNIT_OID","ROLE_OID") VALUES (3, 'Scott ', '41351894', 'M', 'WA', '1985-02-08', 'stiger', 'upload/profile_big.jpg', '2012-10-16', 'Tiger', NULL, 2);

INSERT INTO "APP"."ORGANIZATION_UNIT"("OID","NAME","DESCRIPTION","TYPE","ORGANIZATION_UNIT_OID","EMPLOYEE_OID") VALUES (5, 'Human Resources', 'Human resources', 'Department', NULL, 3);

INSERT INTO "APP"."EMPLOYEE"("USER_OID", "FIRST_NAME","PHONE","GENDER","LOCATION","BIRTHDATE","IM_USERNAME","PIC","ENTRYDATE","LAST_NAME","ORGANIZATION_UNIT_OID","ROLE_OID") VALUES (4, 'Ray', '4561357896', 'M', 'TX', '1978-10-09', 'rherbert', 'upload/profile_big.jpg', '2010-10-16', 'Herbert', NULL, 1);
INSERT INTO "APP"."EMPLOYEE"("USER_OID", "FIRST_NAME","PHONE","GENDER","LOCATION","BIRTHDATE","IM_USERNAME","PIC","ENTRYDATE","LAST_NAME","ORGANIZATION_UNIT_OID","ROLE_OID") VALUES (5, 'Douglas', '45315453', 'M', 'CA', '1989-02-05', 'dmartin', 'upload/profile_big.jpg', '2012-10-16', 'Martin', NULL, 2);

INSERT INTO "APP"."ORGANIZATION_UNIT"("OID","NAME","DESCRIPTION","TYPE","ORGANIZATION_UNIT_OID","EMPLOYEE_OID") VALUES (2, 'Marketing', 'Dep of marketing', 'Department', NULL, 5);
INSERT INTO "APP"."ORGANIZATION_UNIT"("OID","NAME","DESCRIPTION","TYPE","ORGANIZATION_UNIT_OID","EMPLOYEE_OID") VALUES (6, 'Sales', 'Sales management', 'Department Unit', 2, 5);

INSERT INTO "APP"."EMPLOYEE"("USER_OID", "FIRST_NAME","PHONE","GENDER","LOCATION","BIRTHDATE","IM_USERNAME","PIC","ENTRYDATE","LAST_NAME","ORGANIZATION_UNIT_OID","ROLE_OID") VALUES (6, 'Adam ', '5453158531', 'M', 'NY', '1984-06-08', 'ahendricks', 'upload/profile_big.jpg', '2012-10-16', 'Hendricks', NULL, 2);
INSERT INTO "APP"."EMPLOYEE"("USER_OID", "FIRST_NAME","PHONE","GENDER","LOCATION","BIRTHDATE","IM_USERNAME","PIC","ENTRYDATE","LAST_NAME","ORGANIZATION_UNIT_OID","ROLE_OID") VALUES (7, 'Mark', '4684132158486', 'M', 'NY', '1991-10-23', NULL, 'upload/profile_big.jpg', '2012-10-16', 'Walsh', 5, 2);
INSERT INTO "APP"."EMPLOYEE"("USER_OID", "FIRST_NAME","PHONE","GENDER","LOCATION","BIRTHDATE","IM_USERNAME","PIC","ENTRYDATE","LAST_NAME","ORGANIZATION_UNIT_OID","ROLE_OID") VALUES (8, 'James', '684351548', 'M', 'WA', '1989-10-23', NULL, 'upload/profile_big.jpg', '2012-10-16', 'Ning', 6, 2);



INSERT INTO "APP"."ORGANIZATION_UNIT"("OID","NAME","DESCRIPTION","TYPE","ORGANIZATION_UNIT_OID","EMPLOYEE_OID") VALUES (1, 'Finance', 'Dep of Finance', 'Department', NULL, 4);
INSERT INTO "APP"."ORGANIZATION_UNIT"("OID","NAME","DESCRIPTION","TYPE","ORGANIZATION_UNIT_OID","EMPLOYEE_OID") VALUES (3, 'Research', 'Research on finance problems', 'Department Unit', 1, 4);
INSERT INTO "APP"."ORGANIZATION_UNIT"("OID","NAME","DESCRIPTION","TYPE","ORGANIZATION_UNIT_OID","EMPLOYEE_OID") VALUES (4, 'IT', 'Information technology', 'Department', NULL, 6);





